apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: cluster-admin-role-binding
subjects:
- kind: User
  name: admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin-role
  