apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-dashboard-role-binding
subjects:
- kind: ServiceAccount
  name: k8s-dashboard-sa
  apiGroup: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-dashboard-role